plugins:
    rubocop-rspec

AllCops:
    NewCops: enable
    TargetRubyVersion: 2.0
Layout/LineLength:
    Max: 121
Metrics/AbcSize:
    Max: 26
Metrics/BlockLength:
    Max: 53
Metrics/CyclomaticComplexity:
    Max: 12
Metrics/MethodLength:
    Max: 35
Naming/MethodParameterName:
    Enabled: false
Metrics/ParameterLists:
    Max: 7
Metrics/PerceivedComplexity:
    Max: 12
Naming/VariableNumber:
    Enabled: false
RSpec/DescribeClass:
    Enabled: false
RSpec/ExampleLength:
    Max: 18
RSpec/LeakyLocalVariable:
    Enabled: false
RSpec/MessageSpies:
    Enabled: false
RSpec/MultipleDescribes:
    Enabled: false
RSpec/MultipleExpectations:
    Max: 4
RSpec/NoExpectationExample:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false
Style/HashSyntax:
    Enabled: false
